/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author edtvi
 */
public class CollatzSequenceMain extends javax.swing.JFrame {
    MenuForm menuForm;
    int arrayValues[] = new int[100000];
    int initVal0 = 0, initVal1 = 0 , initVal2 = 1;
    /**
     * Creates new form CollatzSequenceMain
     */
    public CollatzSequenceMain() {
        initComponents();
        menuForm = new MenuForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        noTermsLbl = new javax.swing.JLabel();
        initVal = new javax.swing.JTextField();
        alertMsg = new javax.swing.JLabel();
        noTermsLbl1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        answerLbl1 = new javax.swing.JLabel();
        compute = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        solution = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        answer = new javax.swing.JTextArea();
        goBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Collatz Sequence");
        setAlwaysOnTop(true);
        setResizable(false);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));

        noTermsLbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        noTermsLbl.setText("Enter the initial value");
        noTermsLbl.setToolTipText("Enter the limit");

        initVal.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        initVal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 51), 2));

        alertMsg.setBackground(new java.awt.Color(153, 153, 255));
        alertMsg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        alertMsg.setForeground(new java.awt.Color(51, 51, 51));
        alertMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        noTermsLbl1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        noTermsLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noTermsLbl1.setText("Solution");
        noTermsLbl1.setToolTipText("Enter the limit");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        answerLbl1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        answerLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        answerLbl1.setText("C[n] = ");
        answerLbl1.setToolTipText("Enter the limit");

        compute.setBackground(new java.awt.Color(51, 255, 51));
        compute.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        compute.setText("Compute");
        compute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeActionPerformed(evt);
            }
        });

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        solution.setEditable(false);
        solution.setColumns(10);
        solution.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        solution.setLineWrap(true);
        solution.setRows(5);
        solution.setWrapStyleWord(true);
        jScrollPane2.setViewportView(solution);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setAutoscrolls(true);

        answer.setEditable(false);
        answer.setColumns(10);
        answer.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        answer.setLineWrap(true);
        answer.setRows(5);
        answer.setWrapStyleWord(true);
        jScrollPane3.setViewportView(answer);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        goBackBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        goBackBtn.setForeground(new java.awt.Color(255, 0, 0));
        goBackBtn.setText("<-- Go Back");
        goBackBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        goBackBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        goBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1)
                            .addComponent(noTermsLbl1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noTermsLbl, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgPanelLayout.createSequentialGroup()
                                .addComponent(answerLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgPanelLayout.createSequentialGroup()
                                .addComponent(initVal, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(compute, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgPanelLayout.createSequentialGroup()
                                .addComponent(goBackBtn)
                                .addGap(90, 90, 90)
                                .addComponent(alertMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addComponent(goBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(alertMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noTermsLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(compute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(initVal, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(noTermsLbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(answerLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void computeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeActionPerformed
        int initValue = Integer.parseInt(initVal.getText());
        String ans = "", sol = "C[0] = " + String.valueOf(initValue) + ", ";
        int index = 0, counter = 1;
        arrayValues[0] = initValue;
        //validation checking
        if(initValue == 1){
            alertMsg.setText("The initial value you entered is already 1");
            solution.setText("");
            answer.setText("");
            return; 
        }else if(initValue % 2 == 0 ){
            alertMsg.setText("The initial value you entered is not positive odd");
            solution.setText("");
            answer.setText("");
            return;
        }else if(initValue < 1){
            alertMsg.setText("The initial value you entered is invalid");
            solution.setText("");
            answer.setText("");
            return;
        }else{
            alertMsg.setText("");
            while(arrayValues[index] != 1){
                if(arrayValues[index] % 2 != 0 ){
                    arrayValues[index+1] = (3*arrayValues[index]) + 1;
                    sol += "C[" + counter + "] = 3*" + String.valueOf(arrayValues[counter-1]) + " + 1 = " + String.valueOf(arrayValues[index+1]);
                    sol += ", ";
                    counter++;
                }else{
                    arrayValues[index+1] = arrayValues[index] / 2;
                    sol += "C[" + counter + "] = " + String.valueOf(arrayValues[counter-1]) + " / 2 = " + String.valueOf(arrayValues[index+1]);
                    sol += ", ";
                    counter++;
                }
                index++;
            }
        }
        //set the value to gui
        for (int i = 0; i <= index; i++) {
            ans += String.valueOf(arrayValues[i]);
            if(i < index) {
                ans += ", ";
            }
        }
            solution.setText(sol);
            answer.setText(ans);
            initVal.setText("");
        
    }//GEN-LAST:event_computeActionPerformed

    private void goBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackBtnActionPerformed
        menuForm.goToMenu(this);
    }//GEN-LAST:event_goBackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CollatzSequenceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CollatzSequenceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CollatzSequenceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CollatzSequenceMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CollatzSequenceMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertMsg;
    private javax.swing.JTextArea answer;
    private javax.swing.JLabel answerLbl1;
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton compute;
    private javax.swing.JButton goBackBtn;
    private javax.swing.JTextField initVal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel noTermsLbl;
    private javax.swing.JLabel noTermsLbl1;
    private javax.swing.JTextArea solution;
    // End of variables declaration//GEN-END:variables
}
