/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author edtvi
 */
public class MenuForm extends javax.swing.JFrame {

    /**
     * Creates new form MenuForm
     */
    public MenuForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPanel = new javax.swing.JPanel();
        fibonacciNum = new javax.swing.JButton();
        lucasNum = new javax.swing.JButton();
        tribonacciNum = new javax.swing.JButton();
        collatzSeq = new javax.swing.JButton();
        menuLabel = new javax.swing.JLabel();
        goBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Program Menu");
        setAlwaysOnTop(true);
        setResizable(false);

        bgPanel.setBackground(new java.awt.Color(255, 255, 255));

        fibonacciNum.setBackground(new java.awt.Color(0, 153, 153));
        fibonacciNum.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        fibonacciNum.setText("Fibonacci Numbers");
        fibonacciNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fibonacciNumActionPerformed(evt);
            }
        });

        lucasNum.setBackground(new java.awt.Color(0, 204, 0));
        lucasNum.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lucasNum.setText("Lucas Numbers");
        lucasNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lucasNumActionPerformed(evt);
            }
        });

        tribonacciNum.setBackground(new java.awt.Color(255, 255, 51));
        tribonacciNum.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tribonacciNum.setText("Tribonacci Numbers");
        tribonacciNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tribonacciNumActionPerformed(evt);
            }
        });

        collatzSeq.setBackground(new java.awt.Color(204, 0, 204));
        collatzSeq.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        collatzSeq.setText("Collatz Sequence");
        collatzSeq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collatzSeqActionPerformed(evt);
            }
        });

        menuLabel.setBackground(new java.awt.Color(255, 255, 255));
        menuLabel.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        menuLabel.setForeground(new java.awt.Color(51, 51, 51));
        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setText("Choice your desire program");

        goBackBtn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        goBackBtn.setForeground(new java.awt.Color(204, 0, 0));
        goBackBtn.setText("<-- Go Back");
        goBackBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        goBackBtn.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        goBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
        bgPanel.setLayout(bgPanelLayout);
        bgPanelLayout.setHorizontalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgPanelLayout.createSequentialGroup()
                        .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(goBackBtn)
                            .addGroup(bgPanelLayout.createSequentialGroup()
                                .addComponent(fibonacciNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lucasNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tribonacciNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(collatzSeq)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        bgPanelLayout.setVerticalGroup(
            bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(goBackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lucasNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fibonacciNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tribonacciNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(collatzSeq, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackBtnActionPerformed
        this.dispose();
        new MainForm().setVisible(true);
    }//GEN-LAST:event_goBackBtnActionPerformed

    private void fibonacciNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fibonacciNumActionPerformed
        this.dispose();
        new FibonacciNumbers().setVisible(true);
    }//GEN-LAST:event_fibonacciNumActionPerformed

    private void lucasNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lucasNumActionPerformed
        this.dispose();
        new LucasNumbers().setVisible(true);
    }//GEN-LAST:event_lucasNumActionPerformed

    private void tribonacciNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tribonacciNumActionPerformed
        this.dispose();
        new TribonacciNumbers().setVisible(true);
    }//GEN-LAST:event_tribonacciNumActionPerformed

    private void collatzSeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collatzSeqActionPerformed
        this.dispose();
        new CollatzSequence().setVisible(true);
    }//GEN-LAST:event_collatzSeqActionPerformed

    public void goToMenu(JFrame frame) {
        frame.dispose();
        new MenuForm().setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgPanel;
    private javax.swing.JButton collatzSeq;
    private javax.swing.JButton fibonacciNum;
    private javax.swing.JButton goBackBtn;
    private javax.swing.JButton lucasNum;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JButton tribonacciNum;
    // End of variables declaration//GEN-END:variables
}
